# Generated by Django 5.2.8 on 2025-11-29 00:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='id',
        ),
        migrations.AlterField(
            model_name='bridge',
            name='bridge_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='bridge',
            table='bridges',
        ),
    ]
