# Generated by Django 5.2.8 on 2025-11-29 11:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_remove_bridge_id_alter_bridge_bridge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='bridge_id',
            field=models.CharField(help_text='Identifiant unique du pont', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(help_text='Coordonnées géographiques du pont', srid=4326),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='name',
            field=models.CharField(help_text='Nom du pont', max_length=100),
        ),
    ]
